### ISSUE TITLE
Crashes, segmentation fault

### ISSUE THREAD

**Issue by tony37** [sugarlabs/analyze#1]
Tested on Ubuntu 16.04 Sucrose. It appears that this version of Sugar does not  provides a network link. The analyze activity crashes with no report in the Log.

**Comment by quozl** [comment]
Actually, it just crashes, network or not.

```
Terminated by signal 11, pid 7532 data (<open file '<fdopen>', mode 'w'
    at 0x7f2c759456f0>, '22f71b749c869eeead02436f955b55250799c9e2')
```

with a backtrace

```
Thread 1 (Thread 0x7ffff7fc6740 (LWP 1249)):
#0  0x00007fffeffa97fa in XInternAtom () at /usr/lib/x86_64-linux-gnu/libX11.so.6
#1  0x00007ffff31a9e18 in ffi_call_unix64 () at /usr/lib/x86_64-linux-gnu/libffi.so.6
#2  0x00007ffff31a987a in ffi_call () at /usr/lib/x86_64-linux-gnu/libffi.so.6
#3  0x00007fffe5ef5a94 in _ctypes_callproc () at /usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so
#4  0x00007fffe5ef5495 in  () at /usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so
#5  0x000055555564e2d0 in PyEval_EvalFrameEx ()
#6  0x000055555564e0e2 in PyEval_EvalFrameEx ()
#7  0x00005555556467da in PyEval_EvalCodeEx ()
#8  0x000055555564e4ae in PyEval_EvalFrameEx ()
#9  0x00005555556467da in PyEval_EvalCodeEx ()
#10 0x0000555555662429 in  ()
#11 0x000055555567b6ae in  ()
#12 0x000055555567b2ba in  ()
#13 0x000055555563740b in  ()
#14 0x000055555564e2d0 in PyEval_EvalFrameEx ()
#15 0x00005555556467da in PyEval_EvalCodeEx ()
#16 0x0000555555662429 in  ()
#17 0x000055555567b6ae in  ()
#18 0x000055555567b2ba in  ()
#19 0x000055555563740b in  ()
#20 0x000055555564e2d0 in PyEval_EvalFrameEx ()
#21 0x000055555564e0e2 in PyEval_EvalFrameEx ()
#22 0x000055555564e0e2 in PyEval_EvalFrameEx ()
#23 0x00005555556467da in PyEval_EvalCodeEx ()
#24 0x000055555567772f in  ()
#25 0x0000555555672342 in PyRun_FileExFlags ()
#26 0x0000555555671ebd in PyRun_SimpleFileExFlags ()
#27 0x00005555556204f4 in Py_Main ()
#28 0x00007ffff77f71c1 in __libc_start_main (main=
    0x55555561fed0 <main>, argc=3, argv=0x7fffffffd908, init=<optimised out>, fini=<optimised out>, rtld_fini=<optimised out>, stack_end=0x7fffffffd8f8) at ../csu/libc-start.c:308
#29 0x000055555561fdea in _start ()
```

Probably a 32-bit architecture dependency in the code, which hasn't been updated for nine years.

Activity needs a maintainer, or it should be retired and deleted.

**Comment by quozl** [comment]
Given #9, closing this.
